[package]
name = "apca"
version = "0.1.1"
edition = "2018"
authors = ["Daniel Mueller <deso@posteo.net>"]
license = "GPL-3.0-or-later"
homepage = "https://github.com/d-e-s-o/apca"
repository = "https://github.com/d-e-s-o/apca.git"
readme = "README.md"
categories = [
  "api-bindings",
  "asynchronous",
  "network-programming",
  "web-programming::http-client",
  "web-programming::websocket"
]
keywords = ["trading", "finance", "async", "stocks"]
description = """
A create for interacting with the Alpaca API.
"""

[dependencies]
chrono = {version = "0.4", default-features = false}
futures = "0.1"
hyper = "0.12"
hyper-tls = "0.3"
log = "0.4"
num-decimal = {version = "0.1", features = ["serde"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
url = "1.0"
uuid = {version = "0.7", features = ["serde", "v4"]}
websocket = {version = "0.24", default-features = false, features = ["async", "async-ssl"]}

[dev-dependencies]
env_logger = {version = "0.6", default-features = false}
test-env-log = "0.1"
tokio = {version = "0.1", default-features = false, features = ["tcp"]}
